(()=>{"use strict";
document.documentElement.classList.add("js-ready");
const menu=document.getElementById("menuButton"),nav=document.getElementById("siteNav");
if(menu&&nav){menu.addEventListener("click",()=>{const open=nav.classList.toggle("open");menu.setAttribute("aria-expanded",String(open))});nav.addEventListener("click",e=>{if(e.target.closest("a")){nav.classList.remove("open");menu.setAttribute("aria-expanded","false")}})}
const reveals=[...document.querySelectorAll(".reveal")];
if("IntersectionObserver"in window){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("in-view");io.unobserve(e.target)}}),{rootMargin:"0px 0px -8% 0px",threshold:.08});reveals.forEach(el=>io.observe(el))}else reveals.forEach(el=>el.classList.add("in-view"));
const cards=[...document.querySelectorAll(".qa-card")],search=document.getElementById("qaSearch"),count=document.getElementById("qaCount"),empty=document.getElementById("qaEmpty"),buttons=[...document.querySelectorAll(".filter-buttons button")];
const qaList=document.getElementById("qaList"),chapterDefs=[
  {key:"family",prefixes:["family"],title:"第一章｜A童外婆完整證詞"},
  {key:"doctor-caixuan",prefixes:["doctor-caixuan"],title:"第二章｜劉彩萱辯方詰問徐堅棋醫師"},
  {key:"doctor-ruolin",prefixes:["doctor-ruolin"],title:"第三章｜劉若琳辯方詰問徐堅棋醫師"},
  {key:"doctor-prosecutor",prefixes:["doctor-prosecutor"],title:"第四章｜檢察官詰問徐堅棋醫師"},
  {key:"doctor-judge",prefixes:["doctor-judge"],title:"第五章｜審判長詢問徐堅棋醫師"}
];
const crossrefMap={
  "02":[["#family-xref-placement","返回｜出養與照顧轉換勾稽"]],"03":[["#family-xref-placement","返回｜出養與照顧轉換勾稽"]],"06":[["#family-xref-health","返回｜交接前健康勾稽"]],"07":[["#family-xref-health","返回｜交接前健康勾稽"]],"08":[["#family-xref-placement","返回｜出養與照顧轉換勾稽"]],"10":[["#family-xref-contact","返回｜探視與聯繫勾稽"]],"11":[["#family-xref-placement","返回｜出養與照顧轉換勾稽"]],"12":[["#family-xref-health","返回｜交接前健康勾稽"]],"15":[["#family-xref-repair","返回｜事發後修復勾稽"]],"17":[["#family-xref-repair","返回｜事發後修復勾稽"]],"19":[["#family-xref-repair","返回｜事發後修復勾稽"]],
  "28":[["#doctor-xref-self-harm","返回｜自傷說法勾稽"]],"44":[["#doctor-xref-mental-state","返回｜精神自述與治療勾稽"]],"46":[["#doctor-xref-self-harm","返回｜自傷說法勾稽"],["#doctor-xref-responsibility","返回｜責任評價勾稽"]],"48":[["#doctor-xref-mental-state","返回｜精神自述與治療勾稽"]],"50":[["#doctor-xref-mental-state","返回｜精神自述與治療勾稽"]],"51":[["#doctor-xref-recovery","返回｜風險與復歸勾稽"]],"58":[["#doctor-xref-responsibility","返回｜責任評價勾稽"]],"59":[["#doctor-xref-recovery","返回｜風險與復歸勾稽"]],"61":[["#doctor-xref-recovery","返回｜風險與復歸勾稽"]]
};
cards.forEach(card=>{const number=(card.querySelector("header span")?.textContent||"").trim().padStart(2,"0");if(!number)return;card.id="qa-"+number;const links=crossrefMap[number];if(!links)return;const back=document.createElement("nav");back.className="qa-crosslinks";back.setAttribute("aria-label","本題跨證人勾稽");links.forEach(([href,label])=>{const a=document.createElement("a");a.href=href;a.textContent=label;back.appendChild(a)});card.appendChild(back)});
if(qaList&&cards.length){chapterDefs.forEach((def,index)=>{const members=cards.filter(card=>def.prefixes.some(prefix=>(card.dataset.group||"").startsWith(prefix)));if(!members.length)return;const details=document.createElement("details");details.className="qa-chapter";details.open=index<2;details.dataset.chapter=def.key;const summary=document.createElement("summary");summary.textContent=def.title+"・"+members.length+"組";const body=document.createElement("div");body.className="qa-chapter-body";members.forEach(card=>{const label=card.querySelector("header small")?.textContent||def.title;card.setAttribute("aria-label",label);body.appendChild(card)});details.append(summary,body);qaList.appendChild(details)})}
const chapters=[...document.querySelectorAll(".qa-chapter")];
function revealHashTarget(){const id=decodeURIComponent(location.hash.slice(1));if(!id)return;const target=document.getElementById(id);if(!target)return;const chapter=target.closest(".qa-chapter");if(chapter){chapter.hidden=false;chapter.open=true}document.querySelectorAll(".xref-target").forEach(el=>el.classList.remove("xref-target"));target.classList.add("xref-target");requestAnimationFrame(()=>target.scrollIntoView({block:"start",behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"}))}
if(location.hash)setTimeout(revealHashTarget,60);window.addEventListener("hashchange",revealHashTarget);
let mode={type:"all",value:"all"};
function applyFilter(){const term=(search?.value||"").trim().toLocaleLowerCase();let visible=0;cards.forEach(card=>{const group=card.dataset.group||"";const groupOK=mode.type==="all"||mode.type==="exact"&&group===mode.value||mode.type==="prefix"&&group.startsWith(mode.value);const textOK=!term||card.textContent.toLocaleLowerCase().includes(term);card.hidden=!(groupOK&&textOK);if(!card.hidden){visible++;card.classList.add("in-view")}});chapters.forEach(chapter=>{const hasVisible=[...chapter.querySelectorAll(".qa-card")].some(card=>!card.hidden);chapter.hidden=!hasVisible;if(hasVisible&&(term||mode.type!=="all"))chapter.open=true});if(count)count.textContent="顯示 "+visible+" 組問答";const mobileToggle=document.getElementById("mobileFilterToggle");if(mobileToggle)mobileToggle.textContent="搜尋／篩選・顯示 "+visible+" 組";if(empty)empty.hidden=visible!==0}
buttons.forEach(btn=>btn.addEventListener("click",()=>{buttons.forEach(x=>{x.classList.remove("active");x.setAttribute("aria-pressed","false")});btn.classList.add("active");btn.setAttribute("aria-pressed","true");mode=btn.dataset.filter==="all"?{type:"all",value:"all"}:btn.dataset.filter?{type:"exact",value:btn.dataset.filter}:{type:"prefix",value:btn.dataset.filterPrefix};applyFilter()}));search?.addEventListener("input",applyFilter);
const toolsPanel=document.querySelector(".dialogue-tools"),mobileToggle=document.getElementById("mobileFilterToggle");mobileToggle?.addEventListener("click",()=>{const open=toolsPanel.classList.toggle("panel-open");mobileToggle.setAttribute("aria-expanded",String(open))});
document.getElementById("expandAll")?.addEventListener("click",()=>chapters.filter(x=>!x.hidden).forEach(x=>x.open=true));document.getElementById("collapseAll")?.addEventListener("click",()=>chapters.forEach(x=>x.open=false));
const lang=new URLSearchParams(location.search).get("lang")==="zh-Hans"?"zh-Hans":"zh-Hant";
document.documentElement.lang=lang;document.querySelectorAll("[data-language]").forEach(a=>a.setAttribute("aria-current",String(a.dataset.language===lang)));
function applySimplified(){if(lang!=="zh-Hans"||!window.OpenCC?.Converter)return;const convert=OpenCC.Converter({from:"tw",to:"cn"});const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,{acceptNode(node){const p=node.parentElement;if(!p||/^(SCRIPT|STYLE|CODE)$/.test(p.tagName))return NodeFilter.FILTER_REJECT;return node.nodeValue.trim()?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT}});const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>n.nodeValue=convert(n.nodeValue));document.title=convert(document.title)}
if(document.readyState==="complete")applySimplified();else window.addEventListener("load",applySimplified,{once:true});
const copy=document.getElementById("copyCitation");copy?.addEventListener("click",async()=>{const citation="監所關注小組，〈DAY8｜2025年5月5日（一）第八次審判期日〉，護童行動聯盟重製頁："+location.href.split("?")[0];try{await navigator.clipboard.writeText(citation);copy.textContent="已複製來源註記"}catch{copy.textContent="請手動複製網址"}setTimeout(()=>copy.textContent="複製來源註記",2200)});
window.addEventListener("load",()=>{if(!window.gsap||matchMedia("(prefers-reduced-motion: reduce)").matches)return;gsap.registerPlugin(window.ScrollTrigger);if(document.querySelector(".paper-cloud"))gsap.to(".paper-cloud",{x:18,y:-8,duration:5.5,repeat:-1,yoyo:true,ease:"sine.inOut"});if(document.querySelector(".red-thread"))gsap.to(".red-thread",{strokeDashoffset:-90,duration:6,repeat:-1,ease:"none",attr:{"stroke-dasharray":"18 13"}});if(document.querySelector(".dust circle"))gsap.to(".dust circle",{y:-22,opacity:.2,duration:3.5,stagger:.4,repeat:-1,yoyo:true,ease:"sine.inOut"});if(document.querySelector(".stage-ribbons path"))gsap.from(".stage-ribbons path",{scaleX:.82,transformOrigin:"50% 50%",duration:1.1,stagger:.13,ease:"power3.out"})},{once:true});
})();
