"use client";

import {useEffect,useRef,useState} from "react";
import gsap from "gsap";
import {ScrollTrigger} from "gsap/ScrollTrigger";

const timeline=[
 {date:"2020.02.03",title:"完成收養",tag:"媒體報導",copy:"親養子收養申報完成。此後八個月間，入養後追蹤、兒保調查與警察處置陸續留下紀錄。"},
 {date:"2020.05.25",title:"第一次疑似虐待通報",tag:"官方資料／媒體報導",copy:"幼兒園發現身體多處疑似瘀傷後通報。兒保機構判斷存在疏忽照顧並指派個案管理；警方其後內查終結。"},
 {date:"2020.06.29",title:"第二次疑似虐待通報",tag:"官方資料／媒體報導",copy:"孩子被發現單獨留在車內後再次通報。兒保機構與警方未形成足以讓孩子離開原照顧環境的安全決定。"},
 {date:"2020.09.23",title:"第三次疑似虐待通報",tag:"官方資料",copy:"幼兒園及小兒科醫師注意到體重下降、營養狀態與行走能力等異常並報警；孩子最後仍未被分離保護。"},
 {date:"2020.10.13",title:"死亡，年僅16個月",tag:"法院／官方資料",copy:"孩子在首爾陽川區一所醫院死亡。醫院因懷疑兒童虐待而通報警方。"},
 {date:"2021.05.14",title:"一審判決",tag:"法院報導",copy:"首爾南部地方法院認定殺人罪成立，判處養母無期徒刑；養父有期徒刑5年。"},
 {date:"2021.11.26",title:"二審判決",tag:"法院報導",copy:"首爾高等法院維持殺人罪認定，將養母刑度改為35年；養父仍為5年。"},
 {date:"2022.04.28",title:"最高法院定讞",tag:"法院認定",copy:"韓國最高法院駁回上訴，養母35年、養父5年確定。"}
];

const reports=[
 {month:"五月",date:"2020.05.25",known:"幼兒園發現孩子身上多處疑似瘀傷，首次提出虐待疑慮。",action:"兒保機構於當日調查，判斷有疏忽照顧並配置個案管理；警方其後內查終結。",gap:"既有傷勢、照顧說法與後續風險是否已被充分交叉查證？",source:"國家人權委員會人權網誌；韓聯社"},
 {month:"六月",date:"2020.06.29",known:"孩子被發現單獨留在車內，第二次疑似虐待通報出現。",action:"兒保與警方再次介入，但事件沒有累積成更高強度的安全處置。",gap:"第二次通報是否調閱並整合第一次紀錄？照顧環境是否需要重新評估？",source:"國家人權委員會人權網誌；公開報導"},
 {month:"九月",date:"2020.09.23",known:"幼兒園與小兒科醫師注意到體重明顯下降、營養不良及無法獨立行走等異常。",action:"警察與兒保人員曾討論分離，但其後安排至另一家醫院診療，最後以口腔炎症等說明結案。",gap:"醫師的原始疑慮、體重變化與前兩次通報，為何沒有共同形成即時分離與安全覆核？",source:"國家人權委員會人權網誌"}
];

const shadowDialogue=[
 {role:"女",ko:"여인",line:"宮牆外的迎春花又開了，風把花影送進門縫，像有人一次又一次伸手。為何春天知道循時歸來，而孩子的呼聲走過三個季節，仍找不到一扇肯為她完全打開的門？"},
 {role:"男",ko:"광대",line:"因為門內的人各守一盞燈，只照見自己案卷的一角。五月的青痕、六月的孤車、九月消瘦的身影，都被寫進不同的紙頁；紙頁彼此不相識，危險便戴著昨日的面具，重新走了一遍。"},
 {role:"女",ko:"여인",line:"那麼請你告訴我，繁花為何要有五色？若赤只記疼痛、青只記規章、黃只記交接，卻沒有誰把色彩縫在一起，再華美的錦緞，也接不住一個墜落的孩子。"},
 {role:"男",ko:"광대",line:"你說得對。真正的保護不是一紙判斷，而是下一個人接過前一個人的疑問；不是把門合回原位，而是在答案未明以前，讓孩子先站到光裡。"},
 {role:"女",ko:"여인",line:"我不要神明替我們落淚，也不要後世只記住一個名字。我要每次敲門都留下回聲，每道印記都喚醒前一道印記；我要那些尚不能說話的孩子，不必以沉默證明自己的苦難。"},
 {role:"男",ko:"광대",line:"噓，小聲些。宮裡最怕的不是哭聲，是紙頁忽然長了耳朵。若三份卷宗彼此聽見，堂上的大人便不能再說：我只管第一扇門，第二扇門與我無關。"},
 {role:"女",ko:"여인",line:"好個清白的官！眼睛只看印章，耳朵只聽結案，雙手捧著規章，恰好空不出一隻手來抱孩子。若這也算盡責，木偶倒比人高明——至少線一拉，它還知道轉身。"},
 {role:"男",ko:"광대",line:"你莫要取笑木偶。木偶頭上只有一條線，尚且知道線牽向何處；我們的制度有百條線，人人看似忙碌，最後卻把結打在別人的袖口。"},
 {role:"女",ko:"여인",line:"那就把這張倒著的公文呈給滿朝看看：上頭寫著『今日無事』，背面卻密密記著五月、六月、九月。原來字沒有顛倒，顛倒的是讀字的人。"},
 {role:"男",ko:"광대",line:"那便讓今夜的戲不以掌聲作結。待韓紙上的月落下，我們把斷線重新交到看戲的人手裡：下一次，願有人在第三聲以前便起身，在悲劇成為判決以前，先把門打開。"}
];

const royalFood=[
 {ko:"수라상",title:"水剌床",copy:"朝鮮王室日常膳食以多樣菜色、節序與秩序構成。此頁不借宮廷飲食炫示富貴，而用一張完整餐桌反問：每個孩子是否都得到穩定、足量且可被看見的照顧？"},
 {ko:"구절판",title:"九節坂",copy:"九格器皿把不同食材分置，再於中央相合。它在頁面中對應跨機關紀錄：差異可以保留，但資訊必須被放在同一張桌上理解。"},
 {ko:"신선로",title:"神仙爐",copy:"中央火源使食材持續保溫。此處轉譯為持續追蹤：通報不能只在發生當日升溫，之後便迅速冷卻。"}
];

const gisaengArts=[
 {ko:"시조 · 詩調",title:"以詩保存聲音",scene:"月下寫詩",asset:"/gisaeng-paper-poetry.webp",alt:"以韓紙多層紙雕製作的詩箋、墨筆、梅枝與月輪",copy:"妓生藝術不只在舞台，也包含詩文、書寫與唱誦。本頁以留白韓紙象徵：真正值得留下的，不是傳奇人物的容貌，而是她們以藝術獲得發言位置的痕跡。"},
 {ko:"가야금 · 伽倻琴",title:"以絃整理呼吸",scene:"指尖鳴絃",asset:"/gisaeng-paper-gayageum.webp",alt:"以韓紙多層紙雕製作的朝鮮伽倻琴與雲紋",copy:"伽倻琴的絃、長鼓的節拍與舞袖的起落，構成相互回應的秩序。轉譯到案件頁，就是每一項觀察都必須被下一個專業者聽見。"},
 {ko:"춤 · 舞",title:"以身體說出未說之言",scene:"長袖成舞",asset:"/gisaeng-paper-dance.webp",alt:"以韓紙多層紙雕製作的舞扇、彩袖與牡丹",copy:"長袖、扇面與步伐讓情緒取得形狀。這裡只借其美學語彙承載制度追問，不讓華麗服飾掩蓋案件事實。"}
];

const acts=[
 {id:"prologue",no:"序幕",ko:"서막",title:"一只碗先成為問題",narration:"那只白瓷碗被放在桌角。沒有人知道，一只碗空著多久，才會開始像一個問題。早晨先照到桌角，再照到碗沿。日子看起來沒有不同；可是有些不同，只有孩子的身體先知道。",caption:"白瓷碗中的水光逐漸消失。",fact:"本幕是藝術重構，不表示真實現場存在相同器物。",craft:"朝鮮白瓷以節制的白與不完全對稱承載日常；本頁借用它象徵本應穩定存在的照顧。",question:"一個尚不能清楚說話的孩子，身體訊號由誰持續記錄？"},
 {id:"knot",no:"第一幕",ko:"첫째 막",title:"褓布的結",narration:"大人把新的名字寫進表格，把新的關係說成一家人。孩子太小，還不懂得「以後」是什麼。她只懂得今天抱她的手，明天是否還在。",caption:"褓布打結；一根線停在結外。",fact:"2020年2月3日完成收養。收養本身不是傷害原因；焦點是個別犯罪與入養後保護機制。",craft:"褓布與韓國拼布以縫線把不同布片接起。本幕以未穿過的線，表達交接並未形成完整保護。",question:"完成法律關係之後，誰負責持續確認孩子安全？"},
 {id:"reports",no:"第二幕",ko:"둘째 막",title:"三次敲門",narration:"五月，有人敲門。六月，又有人敲門。九月，門外站著第三個人。每一次新的訊號，本應讓門開得更大；可是孩子仍被留在門後。",caption:"三枚紅色章印依序落下，全部保留。",fact:"2020年5月、6月與9月先後出現三次疑似虐待通報。",craft:"赤色方印代表機關決定；圓印代表人的觀察。印記不淡出，象徵紀錄必須累積。",question:"為何每次通報仍像重新從零開始？"},
 {id:"seam",no:"第三幕",ko:"셋째 막",title:"沒有接上的縫線",narration:"每一個人都看見了一小塊。可是一小塊若沒有被縫進下一小塊，就只是一塊布，不是一張能接住孩子的網。",caption:"金色保護線跨越四個機關，於交接處斷裂。",fact:"相關紀錄涉及入養機構、兒保專業機構、警方、幼兒園及醫療人員。",craft:"Jogakbo以透明布片、接縫與負空間構成秩序；此處的斷線不是裝飾，而是制度沒有閉環。",question:"誰應擁有彙整全部訊號並作成安全決定的責任？"},
 {id:"date",no:"第四幕",ko:"넷째 막",title:"十月十三日",narration:"所有來不及被接起來的線，停在同一天。這裡不替她重演疼痛。這裡只記住：那不是沒有預兆的一天。",caption:"所有循環動作停止，只留下日期與冷白光。",fact:"2020年10月13日，孩子死亡，年僅16個月。",craft:"韓紙能讓光穿透，卻不使事實自動透明；冷白留白用來拒絕傷勢奇觀化。",question:"如果第三次通報完成累積風險覆核，結果是否可能不同？"},
 {id:"verdict",no:"第五幕",ko:"다섯째 막",title:"黑漆盒與判決",narration:"判決替罪責寫下年數，卻不能替失去的時間倒數。法律回答了誰應受罰；社會還要回答，下一次誰必須先把門打開。",caption:"黑漆盒開啟，35年與5年由螺鈿碎光中浮現。",fact:"2022年4月28日，韓國最高法院確定養母35年、養父5年。",craft:"螺鈿漆器將薄片嵌入深黑漆面；此處象徵碎裂記憶被保存，不把判決做成勝利慶典。",question:"司法定讞以後，制度改變是否有被持續追蹤？"}
];

function ActNotes({act}:{act:typeof acts[number]}){return <details className="act-notes"><summary>展開本幕完整逐字稿與註解 <span>＋</span></summary><div className="note-grid"><article><b>旁白全文</b><p>{act.narration}</p></article><article><b>畫面字幕</b><p>{act.caption}</p></article><article><b>事實註解</b><p>{act.fact}</p></article><article><b>韓國工藝今解</b><p>{act.craft}</p></article><article><b>制度追問</b><p>{act.question}</p></article><article><b>資料來源</b><p>韓國國家人權委員會人權網誌、韓國最高法院及具名媒體報導；頁尾列出完整連結。</p></article></div></details>}

export default function Home(){
 const root=useRef<HTMLElement>(null);const shadowTimeline=useRef<gsap.core.Timeline|null>(null);const musicTimeline=useRef<gsap.core.Tween|null>(null);const musicCollapseTimer=useRef<number|null>(null);const audioRef=useRef<HTMLAudioElement>(null);const[paused,setPaused]=useState(false);const[shadowPaused,setShadowPaused]=useState(false);const[musicPlaying,setMusicPlaying]=useState(false);const[musicMuted,setMusicMuted]=useState(false);const[musicVolume,setMusicVolume]=useState(.55);const[musicCollapsed,setMusicCollapsed]=useState(false);const[menu,setMenu]=useState(false);const[currentAct,setCurrentAct]=useState("封面／案件專題");const[shadowBeat,setShadowBeat]=useState(0);
 useEffect(()=>{gsap.registerPlugin(ScrollTrigger);if(!root.current||matchMedia("(prefers-reduced-motion: reduce)").matches)return;const ctx=gsap.context(()=>{
  gsap.from(".hero-copy>*",{y:34,opacity:0,duration:1.05,stagger:.12,ease:"power2.out"});gsap.to(".hero-image",{scale:1.035,duration:9,repeat:-1,yoyo:true,ease:"sine.inOut"});
  gsap.from(".music-dock",{y:36,opacity:0,duration:.9,delay:.65,ease:"power2.out"});musicTimeline.current=gsap.to(".music-bar",{scaleY:()=>.3+Math.random()*.7,duration:.42,repeat:-1,yoyo:true,stagger:{each:.09,repeat:-1},ease:"sine.inOut",paused:true});
  const compactReading=matchMedia("(max-width: 760px)").matches;
  gsap.utils.toArray<HTMLElement>(".reveal").forEach(el=>{if(compactReading&&el.closest(".history-essay"))return;gsap.from(el,{y:36,opacity:0,duration:.85,ease:"power2.out",scrollTrigger:{trigger:el,start:"top 84%"}})});
  gsap.utils.toArray<HTMLElement>(".gisaeng-motif").forEach((el,i)=>gsap.fromTo(el,{y:34,rotate:i%2?-2:2,opacity:0},{y:0,rotate:0,opacity:1,duration:1,ease:"power2.out",scrollTrigger:{trigger:el,start:"top 88%"}}));
  gsap.to(".palace-veil",{backgroundPosition:"54% 46%",duration:16,repeat:-1,yoyo:true,ease:"sine.inOut"});
  gsap.timeline({scrollTrigger:{trigger:"#prologue",start:"top 72%"}}).to(".water-glow",{scale:.2,opacity:0,duration:2.4,ease:"power2.in"}).to(".bowl-shadow",{opacity:.42,duration:.8},"<");
  gsap.timeline({scrollTrigger:{trigger:"#knot",start:"top 72%"}}).fromTo(".knot-path",{strokeDashoffset:440},{strokeDashoffset:0,duration:2.6,ease:"power2.inOut"}).to(".loose-thread",{x:38,y:20,rotate:8,duration:1.1,ease:"power2.out"});
  const shadowTl=gsap.timeline({repeat:-1,repeatDelay:.7,scrollTrigger:{trigger:"#shadow-play",start:"top 76%",end:"bottom 10%",toggleActions:"play pause resume pause"}});shadowTimeline.current=shadowTl;
  shadowTl.from(".shadow-curtain",{scaleY:0,duration:1,transformOrigin:"top",ease:"power3.inOut"}).fromTo(".palace-backdrop",{scale:1.12,opacity:0},{scale:1.02,opacity:.5,duration:2,ease:"power2.out"},"-=.7").set(".shadow-pose",{autoAlpha:0}).set(".pose-1",{autoAlpha:1}).fromTo(".pose-1",{xPercent:-3,scale:1.04},{xPercent:0,scale:1,duration:1.4,ease:"power2.out"});
  shadowDialogue.forEach((_,i)=>{const pose=(i<3)?1:(i<7?2:3);shadowTl.call(()=>setShadowBeat(i)).to(`.pose-${pose}`,{autoAlpha:1,duration:.35}).fromTo(".live-dialogue",{autoAlpha:0,y:14,scale:.98},{autoAlpha:1,y:0,scale:1,duration:.38,ease:"power2.out"},"<").to(`.pose-${pose}`,{xPercent:i%2?1.8:-1.8,rotate:i%2?.45:-.45,scale:i%3===0?1.025:1,transformOrigin:i%2?"70% 80%":"30% 80%",duration:1.15,ease:"sine.inOut"},"<").to(".live-dialogue",{autoAlpha:0,y:-8,duration:.25},"+=1.45").to(`.pose-${pose}`,{autoAlpha:i===shadowDialogue.length-1?1:0,duration:.28},"<")});
  shadowTl.to(".shadow-ribbon",{xPercent:180,rotate:12,duration:2.2,ease:"sine.inOut"},"-=2");
  gsap.from(".dialogue-beat",{y:28,opacity:0,duration:.7,stagger:.18,ease:"power2.out",scrollTrigger:{trigger:".dialogue-list",start:"top 82%"}});
  gsap.timeline({scrollTrigger:{trigger:"#reports",start:"top 68%"}}).from(".evidence-stamp",{scale:1.7,opacity:0,rotate:-16,duration:.6,stagger:.65,ease:"back.out(1.5)"}).to(".report-door",{rotateY:0,duration:1.1,stagger:.25,ease:"sine.inOut"},"<.3");
  gsap.timeline({scrollTrigger:{trigger:"#seam",start:"top 68%"}}).fromTo(".stitch-path",{strokeDashoffset:760},{strokeDashoffset:180,duration:2.6,ease:"power2.inOut"}).to(".seam-break",{scale:1,opacity:1,duration:.4,ease:"back.out(2)"});
  gsap.timeline({scrollTrigger:{trigger:"#verdict",start:"top 68%"}}).to(".lacquer-lid",{rotateX:-72,y:-58,duration:1.8,ease:"power2.inOut"}).from(".sentence-number",{y:36,opacity:0,duration:1.1,stagger:.25},"-=.5");
  gsap.timeline({scrollTrigger:{trigger:"#royal-table",start:"top 70%"}}).from(".food-image",{scale:1.14,filter:"saturate(.35)",duration:2.2,ease:"power2.out"}).from(".food-card",{y:42,opacity:0,duration:.8,stagger:.18},"-=1.2");
  const compactGisaeng=matchMedia("(max-width: 900px)").matches;
  gsap.fromTo(".gisaeng-still",{clipPath:"inset(0 18% 0 0)",x:18,opacity:.72},{clipPath:"inset(0 0% 0 0)",x:0,opacity:1,duration:.88,ease:"power3.out",scrollTrigger:{trigger:"#gisaeng-art",start:"top 84%"}});
  gsap.timeline({scrollTrigger:{trigger:"#gisaeng-art",start:"top 76%"}})
   .from(".gisaeng-kicker>*",{y:22,opacity:0,duration:.65,stagger:.12,ease:"power2.out"})
   .from(".gisaeng-intro>*",{y:34,opacity:0,duration:.82,stagger:.13,ease:"power2.out"},"-=.28")
   .from(".gisaeng-scene-tag",{y:18,opacity:0,rotate:2,duration:.55,stagger:.14,ease:"back.out(1.7)"},"-=.48")
   .from(".panorama-paper-layer",{scale:.72,opacity:0,rotate:(i)=>i%2?-8:8,duration:.72,stagger:.13,ease:"back.out(1.7)"},"-=.54");
  gsap.set(".gisaeng-panorama",{scale:1,xPercent:0,yPercent:0,filter:"saturate(1.04)"});
  gsap.fromTo(".gisaeng-still img",{scale:1.1,yPercent:3},{scale:1.015,yPercent:-3,ease:"none",scrollTrigger:{trigger:".gisaeng-gallery",start:"top bottom",end:"bottom top",scrub:1}});
  gsap.fromTo(".gisaeng-progress i",{scaleX:0},{scaleX:1,ease:"none",scrollTrigger:{trigger:"#gisaeng-art",start:"top 70%",end:"bottom 42%",scrub:.7}});
  gsap.to(".panorama-paper-layer.poetry",{yPercent:-8,rotate:-2,duration:5.8,repeat:-1,yoyo:true,ease:"sine.inOut",scrollTrigger:{trigger:"#gisaeng-art",start:"top bottom",end:"bottom top",toggleActions:"play pause resume pause"}});
  gsap.to(".panorama-paper-layer.music",{xPercent:6,scale:1.035,duration:4.6,repeat:-1,yoyo:true,ease:"sine.inOut",scrollTrigger:{trigger:"#gisaeng-art",start:"top bottom",end:"bottom top",toggleActions:"play pause resume pause"}});
  gsap.to(".panorama-paper-layer.dance",{xPercent:-5,yPercent:-5,rotate:4,duration:5.2,repeat:-1,yoyo:true,ease:"sine.inOut",scrollTrigger:{trigger:"#gisaeng-art",start:"top bottom",end:"bottom top",toggleActions:"play pause resume pause"}});
  gsap.utils.toArray<HTMLElement>(".gisaeng-art-card").forEach((card,i)=>{const motif=card.querySelector(".paper-cut-motif");const tl=gsap.timeline({scrollTrigger:{trigger:card,start:"top 88%"}});tl.from(card,{y:compactGisaeng?34:52,opacity:0,rotateX:compactGisaeng?0:-7,transformOrigin:"center bottom",duration:.82,ease:"power2.out"});if(motif){tl.from(motif,{scale:.68,opacity:0,rotate:i===0?-7:i===2?9:0,duration:.72,ease:"back.out(1.7)"},"-=.46");gsap.to(motif,{y:i===1?0:-7,x:i===1?4:0,rotate:i===2?3:i===0?-1:0,scale:i===1?1.025:1,duration:4.2+i*.65,repeat:-1,yoyo:true,ease:"sine.inOut",scrollTrigger:{trigger:card,start:"top bottom",end:"bottom top",toggleActions:"play pause resume pause"}})}});
  gsap.from(".term-note",{y:24,opacity:0,duration:.75,ease:"power2.out",scrollTrigger:{trigger:".term-note",start:"top 90%"}});
  gsap.timeline({scrollTrigger:{trigger:"#action",start:"top 66%"}}).from(".paper-cut-layer",{scale:.86,opacity:0,duration:1.1,ease:"power2.out"}).to(".final-door.left",{xPercent:-102,rotateY:-14,duration:2.2,ease:"power3.inOut"}).to(".final-door.right",{xPercent:102,rotateY:14,duration:2.2,ease:"power3.inOut"},"<").fromTo(".final-hero",{scale:1.14,filter:"brightness(.55)"},{scale:1,filter:"brightness(.78)",duration:2.4,ease:"power2.out"},"-=1.75").from(".final-light>*",{y:24,opacity:0,duration:.9,stagger:.12},"-=1.2");
 },root);const refresh=()=>ScrollTrigger.refresh();const pendingImages=Array.from(root.current.querySelectorAll("img")).filter(img=>!img.complete);pendingImages.forEach(img=>img.addEventListener("load",refresh,{once:true}));const refreshTimer=window.setTimeout(refresh,350);return()=>{window.clearTimeout(refreshTimer);pendingImages.forEach(img=>img.removeEventListener("load",refresh));shadowTimeline.current=null;musicTimeline.current=null;ctx.revert()}},[]);
 useEffect(()=>{const items:Array<[string,string]>=[["#top","封面／案件專題"],["#timeline","案件紀錄"],["#shadow-play","文化章／皮影詩劇"],["#gisaeng-art","文化章／妓生藝術"],...[...acts].map(a=>[`#${a.id}`,`${a.no}／六幕`] as [string,string]),["#royal-table","文化章／宮廷飲食"],["#action","合幕／把門打開"],["#share-kit","分享／繁簡海報"],["#sources","資料／來源"]];const observer=new IntersectionObserver(entries=>{const visible=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>Math.abs(a.boundingClientRect.top-innerHeight/2)-Math.abs(b.boundingClientRect.top-innerHeight/2))[0];if(!visible)return;const item=items.find(([selector])=>visible.target.matches(selector));if(item)setCurrentAct(item[1])},{rootMargin:"-44% 0px -44% 0px",threshold:0});items.forEach(([selector])=>{const el=document.querySelector(selector);if(el)observer.observe(el)});return()=>observer.disconnect()},[]);
 useEffect(()=>{const mobile=matchMedia("(max-width: 760px)");const syncMobileDock=()=>{if(mobile.matches)setMusicCollapsed(true)};const initialSync=window.setTimeout(syncMobileDock,0);mobile.addEventListener("change",syncMobileDock);return()=>{window.clearTimeout(initialSync);mobile.removeEventListener("change",syncMobileDock);if(musicCollapseTimer.current!==null)window.clearTimeout(musicCollapseTimer.current)}},[]);
 useEffect(()=>{gsap.globalTimeline.paused(paused)},[paused]);
 useEffect(()=>{if(audioRef.current){audioRef.current.volume=musicVolume;audioRef.current.muted=musicMuted}},[musicVolume,musicMuted]);
 const skip=()=>{document.querySelector("#action")?.scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"})};
 const toggleShadow=()=>{const tl=shadowTimeline.current;if(!tl)return;const next=!tl.paused();tl.paused(next);setShadowPaused(next)};
 const replayShadow=()=>{shadowTimeline.current?.restart();setShadowPaused(false)};
 const skipShadow=()=>{const tl=shadowTimeline.current;if(!tl)return;tl.pause();setShadowBeat(shadowDialogue.length-1);gsap.set(".shadow-pose",{autoAlpha:0});gsap.set(".pose-3",{autoAlpha:1,xPercent:0,rotate:0,scale:1});gsap.set(".live-dialogue",{autoAlpha:1,y:0,scale:1});setShadowPaused(true)};
 const toggleMusic=async()=>{const audio=audioRef.current;if(!audio)return;if(audio.paused){try{await audio.play();setMusicPlaying(true);musicTimeline.current?.play();if(matchMedia("(max-width: 760px)").matches){if(musicCollapseTimer.current!==null)window.clearTimeout(musicCollapseTimer.current);musicCollapseTimer.current=window.setTimeout(()=>setMusicCollapsed(true),1400)}}catch{setMusicPlaying(false)}}else{audio.pause();setMusicPlaying(false);musicTimeline.current?.pause()}};
 const toggleMusicMute=()=>setMusicMuted(v=>!v);
 return <main ref={root}>
  <audio ref={audioRef} loop preload="metadata" src="/jungein-score.m4a" onPlay={()=>setMusicPlaying(true)} onPause={()=>setMusicPlaying(false)}/>
  <aside id="music-controls" className={`music-dock ${musicCollapsed?"collapsed":""} ${musicPlaying?"is-playing":""}`} aria-label="網頁配樂控制"><button className="music-expand" onClick={()=>setMusicCollapsed(false)} aria-expanded={!musicCollapsed} aria-controls="music-controls" aria-label={musicPlaying?"展開正在播放的配樂控制":"展開配樂控制"}><span aria-hidden="true">♫</span></button><div className="music-art palace-veil" aria-hidden="true"/><div className="music-copy"><small>웹 음악 · WEB SCORE</small><b>돌바닥에 새겨진 그늘</b><span>石地上刻下的影子 · 01:56</span></div><div className="music-bars" aria-hidden="true">{[0,1,2,3].map(x=><i className="music-bar" key={x}/>)}</div><button className="music-primary" onClick={toggleMusic} aria-label={musicPlaying?"暫停配樂":"播放配樂"}>{musicPlaying?"暫停":"播放"}</button><button onClick={toggleMusicMute} aria-label={musicMuted?"開啟聲音":"靜音"}>{musicMuted?"開聲":"靜音"}</button><label><span className="sr-only">音量</span><input aria-label="音量" type="range" min="0" max="1" step="0.05" value={musicVolume} onChange={e=>setMusicVolume(Number(e.target.value))}/></label><button className="music-collapse" onClick={()=>setMusicCollapsed(true)} aria-label="收合配樂控制">收合</button></aside>
  <header className="topbar"><a className="brand" href="#top"><i/>門沒有打開</a><nav className={menu?"open":""}>{[["#timeline","案件時間軸"],["#shadow-play","皮影詩劇"],["#gisaeng-art","妓生藝術"],["#reports","三次通報"],["#royal-table","宮廷飲食"],["#verdict","判決"]].map(x=><a key={x[0]} href={x[0]} onClick={()=>setMenu(false)}>{x[1]}</a>)}</nav><button className="menu-button" aria-expanded={menu} onClick={()=>setMenu(!menu)}>選單</button><div className="controls"><span>{currentAct}</span><button onClick={()=>setPaused(!paused)}>{paused?"繼續":"暫停"}</button><button onClick={skip}>略過動畫</button></div></header>
  <section className="hero" id="top"><picture className="hero-picture"><source media="(max-width:700px)" srcSet="/jeongin-mobile-hero.webp"/><img className="hero-image" src="/jeongin-hanji-hero.webp" alt="韓紙門只開一寸，前方放著白瓷碗、黃銅匙與褓布的藝術重構"/></picture><div className="hero-copy"><p className="eyebrow">SPECIAL PROJECT · KOREA</p><h1>門沒有<br/>打開</h1><p className="hangul">문은 열리지 않았다</p><h2>三次敲門之後，誰仍在門外？</h2><p className="lead">一個孩子不是在沒有訊號的情況下消失。她是在訊號一次次出現、卻沒有形成保護行動時，被留在門後。</p><div className="hero-actions"><a href="#timeline">閱讀案件紀錄</a><a className="ghost" href="#prologue">進入六幕劇場</a></div></div><p className="content-note">內容警示｜本頁涉及兒童虐待與死亡；不呈現施虐過程或真實傷勢。</p></section>

  <section className="timeline section" id="timeline"><div className="section-kicker reveal"><span>CASE RECORD</span><b>案件紀錄</b></div><div className="section-title reveal"><p>先看見事實，再進入藝術敘事</p><h2>八個時間節點，<br/>三次本可介入的時刻。</h2></div><div className="timeline-list">{timeline.map((t,i)=><article className="timeline-item reveal" key={t.date}><span className="timeline-index">{String(i+1).padStart(2,"0")}</span><time>{t.date}</time><div><div className="source-tag">{t.tag}</div><h3>{t.title}</h3><p>{t.copy}</p></div></article>)}</div></section>

  <section className="shadow-play section" id="shadow-play"><div className="section-kicker reveal"><span>그림자극 · SHADOW PLAY</span><b>韓紙月下・十折皮影諷諫劇</b></div><div className="section-title reveal"><p>兩名朝鮮宮廷伶人邊演邊說，以笑聲拆穿彼此不相識的卷宗。</p><h2>花會再開，<br/>門為何沒有打開？</h2></div><div className="shadow-stage reveal"><img loading="lazy" decoding="async" className="shadow-curtain" src="/korean-shadow-theatre.webp" alt="朝鮮宮廷伶人在韓紙月下演出的皮影藝術重構"/><img loading="lazy" decoding="async" className="palace-backdrop" src="/hwang-jini-palace-backdrop.webp" alt="以丹青、伽倻琴、長鼓、舞扇與彩袖構成的半透明朝鮮宮廷舞台"/><img loading="lazy" decoding="async" className="shadow-pose pose-1" src="/shadow-pose-bow.webp" alt="男伶拱手進場、女伶揚袖轉身的皮影動作"/><img loading="lazy" decoding="async" className="shadow-pose pose-2" src="/shadow-pose-scroll.webp" alt="女伶指向紙門、男伶倒持空白公文的諷諫皮影動作"/><img loading="lazy" decoding="async" className="shadow-pose pose-3" src="/shadow-pose-finale.webp" alt="兩名伶人朝向觀眾並指向開門光線的合幕皮影動作"/><i className="shadow-ribbon"/><div className="stage-title"><span>제1장 · 第一場</span><b>月下問門</b></div><article className={`live-dialogue ${shadowDialogue[shadowBeat].role==="女"?"woman":"man"}`} aria-live="polite"><header><b>{shadowDialogue[shadowBeat].role}</b><small>{shadowDialogue[shadowBeat].ko} · {String(shadowBeat+1).padStart(2,"0")}</small></header><p>{shadowDialogue[shadowBeat].line}</p></article></div><div className="shadow-controls" aria-label="皮影劇播放控制"><button onClick={toggleShadow}>{shadowPaused?"繼續播放":"暫停"}</button><button onClick={replayShadow}>重新播放</button><button onClick={skipShadow}>略過動畫</button><span>{String(shadowBeat+1).padStart(2,"0")}／{shadowDialogue.length}</span></div><div className="gisaeng-motifs" aria-label="朝鮮妓生樂舞文化元素"><figure className="gisaeng-motif fan"><span>부채춤</span><b>扇舞 · 舞袖</b></figure><figure className="gisaeng-motif gayageum"><span>가야금</span><b>伽倻琴 · 絃聲</b></figure><figure className="gisaeng-motif dancheong"><span>단청</span><b>丹青 · 月門</b></figure></div><details className="shadow-transcript"><summary>展開十折完整逐字稿 <span>＋</span></summary><div className="dialogue-list">{shadowDialogue.map((d,i)=><article className={`dialogue-beat ${d.role==="女"?"woman":"man"}`} key={i}><header><span>{d.role}</span><small>{d.ko} · {String(i+1).padStart(2,"0")}</small></header><p>{d.line}</p></article>)}</div><div className="shadow-note"><b>創作與文化設定</b><p>半透明舞台借用《黃真伊》所喚起的朝鮮妓生樂舞文化，以彩袖、扇舞、伽倻琴、長鼓與髮飾形成五方色層次；不複製劇中角色、演員或場景。皮影台詞均為本站原創，採宮廷伶人的荒誕諷諫，不引用《王的男人》原台詞。</p></div></details></section>

  <section className="gisaeng-art section" id="gisaeng-art"><div className="gisaeng-progress" aria-hidden="true"><i/>{gisaengArts.map((x,i)=><span key={x.ko}><img src={x.asset} alt=""/><em>{["시","현","무"][i]}</em></span>)}</div><div className="section-kicker gisaeng-kicker"><span>기생 예술 · GISAENG ARTS</span><b>詩、絃、舞：朝鮮女性藝人的文化記憶</b></div><div className="section-title gisaeng-intro"><p>「妓生」是朝鮮歷史中的專業女性藝人，不能直接等同日本藝妓。本章呈現其詩文、音樂與舞蹈，也保留制度限制與史料的不確定。</p><h2>華服不是裝飾，<br/>藝術曾是她們的聲音。</h2></div><div className="gisaeng-gallery"><div className="gisaeng-wide"><img loading="lazy" decoding="async" className="gisaeng-panorama" src="/gisaeng-arts-triptych.webp" alt="完整全景：以韓紙紙雕呈現扇舞、伽倻琴與月下詩文的朝鮮妓生藝術三聯景"/><img className="panorama-paper-layer poetry" src={gisaengArts[0].asset} alt="" aria-hidden="true"/><img className="panorama-paper-layer music" src={gisaengArts[1].asset} alt="" aria-hidden="true"/><img className="panorama-paper-layer dance" src={gisaengArts[2].asset} alt="" aria-hidden="true"/><div className="gisaeng-scene-rail" aria-hidden="true">{gisaengArts.map((x,i)=><span className="gisaeng-scene-tag" key={x.scene}><img src={x.asset} alt=""/><b>{["壹","貳","參"][i]}</b>{x.scene}</span>)}</div><p><span>詩 · 絃 · 舞</span><b>以五方色保存不只一種女性聲音</b></p></div><figure className="gisaeng-still"><div><img loading="lazy" decoding="async" src="/gisaeng-artistry-still.webp" alt="朝鮮妓生藝術的韓服、髮簪、舞扇、伽倻琴、長鼓與筆墨靜物"/><span aria-hidden="true">藝<br/>術<br/>之<br/>器</span></div><figcaption>服飾與器物為藝術重構；不指涉案件人物或特定戲劇角色。</figcaption></figure></div><div className="gisaeng-art-grid">{gisaengArts.map((x,i)=><article className={`gisaeng-art-card art-${i+1}`} key={x.ko}><div className="art-motion"><img loading="lazy" decoding="async" className="paper-cut-motif" src={x.asset} alt={x.alt}/></div><span>{x.ko}</span><h3>{x.title}</h3><p>{x.copy}</p></article>)}</div>
   <article className="history-essay" id="gisaeng-history-essay"><header className="history-essay-head reveal"><div><span>HISTORICAL ESSAY · 韓國文化史</span><b>公開文章 · 2026.08.26</b></div><h2>Gisaeng Arts｜<br/>漂泊、凝視與女性主體性</h2><p>釜山甘川文化村 × 黃真伊</p></header><figure className="history-hero reveal"><picture><source media="(max-width:700px)" srcSet="/social/gisaeng-arts-zh-hant.png"/><img loading="lazy" decoding="async" src="/social/gisaeng-arts-zh-hant.png" alt="韓紙紙雕主視覺：漂泊、凝視與女性主體性，釜山甘川文化村與黃真伊"/></picture><figcaption>甘川文化村是本文的當代觀看入口，並非黃真伊生平地點；畫面為編輯藝術重構。</figcaption></figure><div className="history-lead reveal"><p>一座沿山而築的村落，讓屋舍、坡道與人的生活互相凝視；一位在史料與傳說之間留下詩句的女性，則讓我們追問：當女性長期被觀看，她能否也成為觀看世界、命名情感的人？</p><blockquote>藝術不是替歷史塗上浪漫色彩，而是讓被觀看的人，重新取得觀看世界的位置。</blockquote></div><div className="history-body"><section className="reveal"><span>01 · CONTEMPORARY FRAME</span><h3>從山城巷弄開始：甘川不是布景</h3><p>釜山甘川文化村曾是戰時避難者落腳的生活聚落。2009年起，社區藝術計畫讓閒置房舍與巷弄逐步成為公共創作空間；然而它至今仍是居民日常所在，不是一座為觀光凝固的攝影棚。</p><p>本文把甘川作為「城市如何保存記憶」的當代入口：層疊屋舍像層疊史料，每一面牆都提醒我們，美感不能抹去生活的重量。</p></section><section className="reveal"><span>02 · BETWEEN RECORD & LEGEND</span><h3>黃真伊：在傳說與作品之間</h3><p>黃真伊是朝鮮前期開城的妓生，亦以明月之名流傳，擅長詩、書與音樂。她的生卒年代並不確定，直接記錄有限；後世故事極多，閱讀時必須把可考作品與傳奇敘事分開。</p><p>現存時調數量不多，卻足以讓一個女性聲音穿過制度縫隙：愛欲、離別與時間不再只是他人投向她的目光，而成為她回望世界的語言。</p></section><section className="reveal"><span>03 · EDITORIAL READING</span><h3>被觀看的人，也留下觀看世界的語言</h3><p>以下是編輯詮釋，而非傳記斷言：黃真伊的文化意義，不只來自後世賦予她的傳奇容貌，更在於作品留下的觀看位置。她可以欲求、拒絕、嘲諷，也能把無常寫成自己的尺度。</p><p>當詩句從陪侍技藝轉為可傳誦文本，女性不再只是情節中的風景。她成為敘述者，也讓今日讀者看見，主體性有時並非宏大的宣言，而是仍能以自己的語調說出「我」。</p></section><section className="reveal"><span>04 · ART & CONSTRAINT</span><h3>華服之外：制度、技藝與限制</h3><p>妓生是朝鮮社會中接受詩樂舞訓練的專業女性藝人，與日本藝妓所屬的制度、時代和文化傳統不同。精湛技藝曾提供有限的發言空間，卻不等於她們擁有自由選擇的生活。</p><p>因此，本文同時保留兩件事：承認她們的藝術能動性，也不以華服、才情與愛情傳說遮蔽階序、性別與身分限制。浪漫可以是閱讀的入口，不能成為歷史的結論。</p></section></div><footer className="history-foot"><b>閱讀方法</b><p>文中「女性主體性」屬編輯分析；人物生平以韓國學中央研究院資料為基礎，甘川文化村沿革以釜山官方旅遊資料校準。</p></footer></article>
   <aside className="term-note"><b>用詞說明</b><p>中文常以「韓國藝妓」泛稱，但本頁採歷史稱呼「妓生（기생）」。兩者所屬社會制度、訓練傳統與歷史脈絡不同，不宜直接互換。</p></aside></section>

  <section className="act prologue section" id="prologue"><div className="act-head reveal"><div><span>{acts[0].no} · {acts[0].ko}</span><h2>{acts[0].title}</h2></div><p>{acts[0].narration}</p></div><div className="bowl-stage reveal"><img src="/korean-craft-triptych.webp" alt="韓紙、拼布、粉青沙器與白瓷碗的韓國工藝三聯藝術"/><div className="water-glow"/><div className="bowl-shadow"/><p>백자 · 白瓷<br/><small>水光消失，日常開始成為問題</small></p></div><ActNotes act={acts[0]}/></section>

  <section className="act knot section" id="knot"><div className="act-head reveal"><div><span>{acts[1].no} · {acts[1].ko}</span><h2>{acts[1].title}</h2></div><p>{acts[1].narration}</p></div><div className="knot-stage reveal"><img src="/korean-craft-triptych.webp" alt="韓紙、韓服衣領與褓布縫線的韓國工藝藝術"/><svg viewBox="0 0 900 420" aria-hidden="true"><path className="knot-path" pathLength="440" d="M80 280 C180 80 380 90 430 225 C480 365 620 340 630 200 C640 80 460 80 430 220 C405 335 230 350 165 245"/><path className="loose-thread" d="M632 202 C700 180 760 210 815 160"/></svg><div className="knot-label">結已形成，<br/>仍有一根線沒有穿過。</div></div><ActNotes act={acts[1]}/></section>

  <section className="act reports section" id="reports"><div className="act-head reveal"><div><span>{acts[2].no} · {acts[2].ko}</span><h2>{acts[2].title}</h2></div><p>{acts[2].narration}</p></div><div className="evidence-grid">{reports.map((r,i)=><article className="evidence-card reveal" key={r.month}><header><div className="evidence-stamp">{i+1}</div><div><span>{r.month}</span><time>{r.date}</time></div><div className="report-door" aria-hidden="true"/></header><dl><div><dt>當時已知的警訊</dt><dd>{r.known}</dd></div><div><dt>警察、兒保或醫療處置</dt><dd>{r.action}</dd></div><div><dt>仍未排除的安全問題</dt><dd>{r.gap}</dd></div></dl><footer>{r.source}</footer></article>)}</div><div className="stamp-ledger reveal"><span className="evidence-stamp">1</span><i/><span className="evidence-stamp">2</span><i/><span className="evidence-stamp">3</span><b>三次紀錄同時保留，不再歸零</b></div><ActNotes act={acts[2]}/></section>

  <section className="act seam section" id="seam"><div className="act-head reveal"><div><span>{acts[3].no} · {acts[3].ko}</span><h2>{acts[3].title}</h2></div><p>{acts[3].narration}</p></div><div className="patchwork reveal"><img src="/korean-craft-triptych.webp" alt="Jogakbo拼布與未接上的金色縫線"/><div className="patch-labels"><span>通報者</span><span>警察</span><span>兒童保護</span><span>醫療</span></div><svg viewBox="0 0 900 330" preserveAspectRatio="none" aria-hidden="true"><path className="stitch-path" pathLength="760" d="M30 235 C180 40,280 280,430 105 S680 285,870 70"/><circle className="seam-break" cx="625" cy="199" r="17"/></svg></div><div className="seam-question reveal"><p>看到一小塊，不等於看見孩子所處的全部風險。</p><strong>誰負責把四塊紀錄縫成一張真正的安全網？</strong></div><ActNotes act={acts[3]}/></section>

  <section className="royal-table section" id="royal-table"><div className="section-kicker reveal"><span>궁중음식 · ROYAL CUISINE</span><b>大長今所映照的照顧倫理</b></div><div className="food-layout"><div className="food-visual reveal"><img className="food-image" src="/joseon-royal-cuisine.webp" alt="以鍮器、九節坂、神仙爐與季節菜構成的朝鮮王室飲食藝術重構"/><div><span>五味 · 五色 · 五行</span><strong>一道膳食，是被反覆確認的照顧。</strong></div></div><div className="food-copy reveal"><h2>不是盛宴，<br/>是一張不該缺席的餐桌。</h2><p>《大長今》使許多人看見宮廷料理背後的節序、衛生、選材與責任。本頁借用這套文化記憶，不重演戲劇情節；把烹調中的「確認、交接、留意變化」轉譯成兒童保護語言。</p></div></div><div className="food-grid">{royalFood.map(x=><article className="food-card" key={x.ko}><span>{x.ko}</span><h3>{x.title}</h3><p>{x.copy}</p></article>)}</div><p className="food-source">文化資料：韓國官方 Korea.net「The Royal Table of the Joseon Dynasty」；視覺為藝術重構，並非案件現場或特定劇集畫面。</p></section>

  <section className="act date section" id="date"><div className="date-still"><p>2020</p><h2>十月十三日</h2><p className="hangul">10월 13일</p><div/><blockquote>{acts[4].narration}</blockquote></div><ActNotes act={acts[4]}/></section>

  <section className="act verdict section" id="verdict"><div className="verdict-visual reveal"><img src="/najeon-verdict-box.webp" alt="開啟的韓國螺鈿黑漆盒與赤色文件繩藝術重構"/><div className="lacquer-lid"/><div className="numbers"><span className="sentence-number">35<small>年</small></span><span className="sentence-number">5<small>年</small></span></div></div><div className="verdict-copy reveal"><span>{acts[5].no} · {acts[5].ko}</span><p className="kicker">2022.04.28 · 韓國最高法院定讞</p><h2>{acts[5].title}</h2><p>{acts[5].narration}</p><div className="verdict-facts"><b>養母　35年</b><b>養父　5年</b></div></div><ActNotes act={acts[5]}/></section>

  <section className="action section" id="action"><div className="final-stage"><img loading="lazy" decoding="async" className="final-hero" src="/jeongin-hanji-hero.webp" alt="本案主視覺：韓紙門、白瓷碗、黃銅匙與褓布"/><div className="paper-cut-layer" aria-hidden="true"/><div className="final-door left"><img loading="lazy" decoding="async" src="/hanji-paper-cut-door.webp" alt="" aria-hidden="true"/></div><div className="final-door right"><img loading="lazy" decoding="async" src="/hanji-paper-cut-door.webp" alt="" aria-hidden="true"/></div><div className="final-light"><span>合幕 · 끝막</span><h2>為了下一個孩子，<br/>把門打開得更早。</h2><p>紙雕門扇完全開啟，最後留下本案主視覺。我們不能替她補寫沒有說完的話，但可以讓每一次通報，不再從零開始。</p></div></div><div className="action-grid reveal">{[["辨識","反覆受傷、說法矛盾、體重或行為顯著變化，都需要專業評估。"],["通報","不要等待「確定」才通報；留下時間、觀察與已採取的行動。"],["追蹤","每次新通報都應調閱前次紀錄，重新完成累積風險與即時安全評估。"],["問責","持續檢視案件串接、跨機關會商、分離保護與主管覆核機制。"]].map((x,i)=><article key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section>

  <section className="share-kit section" id="share-kit"><div className="section-kicker reveal"><span>SOCIAL KIT</span><b>韓國文化史專題 · 繁簡海報</b></div><div className="share-heading reveal"><div><p>16:9 EDITORIAL POSTER</p><h2>把她留下的聲音，<br/>帶回今日的觀看。</h2></div><p>兩版主視覺以韓紙紙雕、甘川山城、月輪、詩筆與伽倻琴構成。適合 Threads 連結預覽、橫幅分享與桌面主視覺。</p></div><div className="share-grid landscape"><figure className="share-card reveal"><img loading="lazy" decoding="async" width="1680" height="945" src="/social/gisaeng-arts-zh-hant.png" alt="繁體中文版主視覺海報：漂泊、凝視與女性主體性"/><figcaption><div><span>繁體中文版</span><small>16:9 PNG · 韓國文化史專題</small></div><a href="/social/gisaeng-arts-zh-hant.png" download>下載海報</a></figcaption></figure><figure className="share-card reveal"><img loading="lazy" decoding="async" width="1680" height="945" src="/social/gisaeng-arts-zh-hans.png" alt="简体中文版主视觉海报：漂泊、凝视与女性主体性"/><figcaption><div><span>簡體中文版</span><small>16:9 PNG · 韩国文化史专题</small></div><a href="/social/gisaeng-arts-zh-hans.png" download>下載海報</a></figcaption></figure></div><p className="share-note">海報為韓紙紙雕藝術重構，不指涉真人演員或特定戲劇角色。轉貼時請保留文章連結及「史實／編輯詮釋」的區分。</p></section>

  <section className="sources section" id="sources"><div className="section-kicker"><span>SOURCES</span><b>資料來源與編輯說明</b></div><div className="source-list"><a href="https://encykorea.aks.ac.kr/Article/E0065346" target="_blank" rel="noreferrer"><span>人物史料</span>韓國學中央研究院《韓國民族文化大百科》：黃真伊</a><a href="https://www.visitbusan.net/index.do?lang_cd=en&menuCd=DOM_000000202002001000&uc_seq=2388" target="_blank" rel="noreferrer"><span>官方文化</span>Visit Busan：甘川文化村沿革、社區藝術與工坊</a><a href="https://www.scourt.go.kr/portal/news/NewsViewAction.work?gubun=2&seqnum=4489" target="_blank" rel="noreferrer"><span>法院認定</span>韓國最高法院：養母35年、養父5年確定</a><a href="https://www.humanrights.go.kr/webzine/webzineListAndDetail?boardNo=7606229&issueNo=7606236" target="_blank" rel="noreferrer"><span>官方／人權</span>韓國國家人權委員會：可避免的16個月收養兒死亡，問題在哪裡</a><a href="https://www.yna.co.kr/view/AKR20210107021800004" target="_blank" rel="noreferrer"><span>具名報導</span>韓聯社：入養機構、兒保與警方處置紀錄</a><a href="https://www.korea.net/K-InfoHub/SubMainDetail/view?articleId=4077&headwordCd=68&headwordGroupCd=27&pageIndex=1" target="_blank" rel="noreferrer"><span>官方文化</span>Korea.net：朝鮮王室水剌床與十二碟飯床</a><a href="https://archive.gugak.go.kr/portal/detail/searchVideoAiDetail?clipid=V007869&recording_type_code=V&system_id=AI" target="_blank" rel="noreferrer"><span>官方文化</span>韓國國立國樂院典藏：扇舞與傳統音樂演出資料</a></div><p className="editorial-note">網站以公開資料建立事實骨架；韓紙門、白瓷碗、褓布、皮影、妓生樂舞、宮廷膳食與黑漆盒均屬藝術重構，不表示真實現場存在相同物件。文化史文章把可考資料、後世傳說與編輯詮釋分開，不將妓生簡化為日本藝妓，也不以才情和華服浪漫化其制度處境。</p></section>
  <footer className="site-footer"><p>문을 더 일찍 열어야 한다.</p><p>為了下一個孩子，我們必須更早把門打開。</p></footer>
 </main>
}
